// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	fluttersdk "github.com/bitrise-io/go-flutter/fluttersdk"
	mock "github.com/stretchr/testify/mock"
)

// SDKVersionLister is an autogenerated mock type for the SDKVersionLister type
type SDKVersionLister struct {
	mock.Mock
}

// ListReleasesByChannel provides a mock function with given fields: platform, architecture
func (_m *SDKVersionLister) ListReleasesByChannel(platform fluttersdk.Platform, architecture fluttersdk.Architecture) (map[string][]fluttersdk.Release, error) {
	ret := _m.Called(platform, architecture)

	var r0 map[string][]fluttersdk.Release
	var r1 error
	if rf, ok := ret.Get(0).(func(fluttersdk.Platform, fluttersdk.Architecture) (map[string][]fluttersdk.Release, error)); ok {
		return rf(platform, architecture)
	}
	if rf, ok := ret.Get(0).(func(fluttersdk.Platform, fluttersdk.Architecture) map[string][]fluttersdk.Release); ok {
		r0 = rf(platform, architecture)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]fluttersdk.Release)
		}
	}

	if rf, ok := ret.Get(1).(func(fluttersdk.Platform, fluttersdk.Architecture) error); ok {
		r1 = rf(platform, architecture)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSDKVersionLister interface {
	mock.TestingT
	Cleanup(func())
}

// NewSDKVersionLister creates a new instance of SDKVersionLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSDKVersionLister(t mockConstructorTestingTNewSDKVersionLister) *SDKVersionLister {
	mock := &SDKVersionLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
